cargo run --release -- -t 12 -p bfsstbs labyrinthe0.txt >> outputs/labyrinthe0.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe1.txt >> outputs/labyrinthe1.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe2.txt >> outputs/labyrinthe2.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe3.txt >> outputs/labyrinthe3.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe4.txt >> outputs/labyrinthe4.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe5.txt >> outputs/labyrinthe5.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe6.txt >> outputs/labyrinthe6.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe7.txt >> outputs/labyrinthe7.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe8.txt >> outputs/labyrinthe8.output.st.txt
cargo run --release -- -t 12 -p bfsstbs labyrinthe9.txt >> outputs/labyrinthe9.output.st.txt