cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe0.txt >> outputs/labyrinthe0.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe1.txt >> outputs/labyrinthe1.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe2.txt >> outputs/labyrinthe2.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe3.txt >> outputs/labyrinthe3.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe4.txt >> outputs/labyrinthe4.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe5.txt >> outputs/labyrinthe5.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe6.txt >> outputs/labyrinthe6.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe7.txt >> outputs/labyrinthe7.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe8.txt >> outputs/labyrinthe8.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtcsbs labyrinthe9.txt >> outputs/labyrinthe9.outpu4t.mtcsbs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe0.txt >> outputs/labyrinthe0.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe1.txt >> outputs/labyrinthe1.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe2.txt >> outputs/labyrinthe2.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe3.txt >> outputs/labyrinthe3.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe4.txt >> outputs/labyrinthe4.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe5.txt >> outputs/labyrinthe5.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe6.txt >> outputs/labyrinthe6.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe7.txt >> outputs/labyrinthe7.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe8.txt >> outputs/labyrinthe8.output4.mtabs.txt
cargo run --release -- -t 4 -p bfsmtabs labyrinthe9.txt >> outputs/labyrinthe9.output4.mtabs.txt